/**
 * Navigation data for the application
 * Contains all navigation categories and their respective items
 * 
 * @module constants/navigation
 */

import type { NavigationCategory } from '../types/navigation';

// Category groups for better organization
export const CATEGORY_GROUPS: Record<string, string[]> = {
  'Core': ['React Hooks', 'Patterns', 'Architectures', 'State Management'],
  'Development': ['JavaScript', 'TypeScript', 'Testing', 'Build Tools'],
  'Backend & APIs': ['GraphQL & APIs', 'Real-Time', 'Data Fetching & ORMs', 'Authentication'],
  'Infrastructure': ['DevOps & Tools', 'Cloud', 'CI/CD', 'Security'],
  'Specialized': ['UI Libraries', 'Mobile Development', 'PWA', 'Performance'],
  'Fundamentals': ['Data Structures', 'Algorithms', 'Software Design'],
  'Next.js & React': ['React APIs', 'Next.js APIs'],
  'Other': ['Guides', 'Validation', 'Soft Skills', 'Methodologies'],
};

export const NAVIGATION_DATA: NavigationCategory = {
  'React Hooks': [
    { name: 'useState', href: '/hooks/useState' },
    { name: 'useEffect', href: '/hooks/useEffect' },
    { name: 'useContext', href: '/hooks/useContext' },
    { name: 'useReducer', href: '/hooks/useReducer' },
    { name: 'useCallback', href: '/hooks/useCallback' },
    { name: 'useMemo', href: '/hooks/useMemo' },
    { name: 'useRef', href: '/hooks/useRef' },
    { name: 'useLayoutEffect', href: '/hooks/useLayoutEffect' },
    { name: 'useImperativeHandle', href: '/hooks/useImperativeHandle' },
    { name: 'useDebugValue', href: '/hooks/useDebugValue' },
    { name: 'useDeferredValue', href: '/hooks/useDeferredValue' },
    { name: 'useTransition', href: '/hooks/useTransition' },
    { name: 'useId', href: '/hooks/useId' },
    { name: 'useSyncExternalStore', href: '/hooks/useSyncExternalStore' },
    { name: 'useInsertionEffect', href: '/hooks/useInsertionEffect' },
    { name: 'use', href: '/hooks/use' },
  ],
  'Patterns': [
    { name: 'Compound Components', href: '/patterns/compound-components' },
    { name: 'Higher-Order Component', href: '/patterns/higher-order-component' },
    { name: 'Render Props', href: '/patterns/render-props' },
    { name: 'Container/Presentational', href: '/patterns/container-presentational' },
    { name: 'Provider Pattern', href: '/patterns/provider-pattern' },
    { name: 'Custom Hooks', href: '/patterns/custom-hooks' },
    { name: 'Controlled vs Uncontrolled', href: '/patterns/controlled-uncontrolled' },
    { name: 'State Reducer', href: '/patterns/state-reducer' },
    { name: 'Props Getter', href: '/patterns/props-getter' },
    { name: 'Conditional Rendering', href: '/patterns/conditional-rendering' },
    { name: 'Layout Pattern', href: '/patterns/layout-pattern' },
    { name: 'Observer Pattern', href: '/patterns/observer-pattern' },
    { name: 'Module Pattern', href: '/patterns/module-pattern' },
    { name: 'Singleton Pattern', href: '/patterns/singleton-pattern' },
    { name: 'Proxy Pattern', href: '/patterns/proxy-pattern' },
    { name: 'Factory Pattern', href: '/patterns/factory-pattern' },
    { name: 'Adapter Pattern', href: '/patterns/adapter-pattern' },
    { name: 'Decorator Pattern', href: '/patterns/decorator-pattern' },
    { name: 'Strategy Pattern', href: '/patterns/strategy-pattern' },
    { name: 'Command Pattern', href: '/patterns/command-pattern' },
    { name: 'Facade Pattern', href: '/patterns/facade-pattern' },
  ],
  'Architectures': [
    { name: 'Atomic Design', href: '/architectures/atomic-design' },
    { name: 'Feature-Sliced Design', href: '/architectures/feature-sliced-design' },
    { name: 'Micro Frontends', href: '/architectures/micro-frontends' },
    { name: 'Clean Architecture', href: '/architectures/clean-architecture' },
    { name: 'Hexagonal Architecture', href: '/architectures/hexagonal-architecture' },
    { name: 'Layered Architecture', href: '/architectures/layered-architecture' },
    { name: 'Microservices Architecture', href: '/architectures/microservices-architecture' },
    { name: 'MVC Architecture', href: '/architectures/mvc-architecture' },
  ],
  'State Management': [
    { name: 'Redux Toolkit', href: '/state-management/redux-toolkit' },
    { name: 'Zustand', href: '/state-management/zustand' },
    { name: 'React Hooks', href: '/state-management/react-hooks' },
  ],
  'React APIs': [
    { name: 'React.createElement', href: '/react-apis/createElement' },
    { name: 'React.Children', href: '/react-apis/Children' },
    { name: 'React.Fragment', href: '/react-apis/Fragment' },
    { name: 'React.memo', href: '/react-apis/memo' },
    { name: 'React.lazy & Suspense', href: '/react-apis/lazy-suspense' },
    { name: 'React.StrictMode', href: '/react-apis/StrictMode' },
    { name: 'React.createRef', href: '/react-apis/createRef' },
    { name: 'React.forwardRef', href: '/react-apis/forwardRef' },
    { name: 'React.cloneElement', href: '/react-apis/cloneElement' },
    { name: 'React.isValidElement', href: '/react-apis/isValidElement' },
    { name: 'React.Component', href: '/react-apis/Component' },
    { name: 'React.PureComponent', href: '/react-apis/PureComponent' },
    { name: 'React.Profiler', href: '/react-apis/Profiler' },
    { name: 'React.startTransition', href: '/react-apis/startTransition' },
    { name: 'React.createPortal', href: '/react-apis/createPortal' },
    { name: 'React.createContext', href: '/react-apis/createContext' },
  ],
  'Next.js APIs': [
    { name: 'next/link', href: '/nextjs-apis/link' },
    { name: 'next/router', href: '/nextjs-apis/router' },
    { name: 'next/image', href: '/nextjs-apis/image' },
    { name: 'next/script', href: '/nextjs-apis/script' },
    { name: 'next/head', href: '/nextjs-apis/head' },
    { name: 'next/dynamic', href: '/nextjs-apis/dynamic' },
    { name: 'next/navigation', href: '/nextjs-apis/navigation' },
    { name: 'next/headers', href: '/nextjs-apis/headers' },
    { name: 'next/server', href: '/nextjs-apis/server' },
    { name: 'next/font', href: '/nextjs-apis/font' },
    { name: 'next/config', href: '/nextjs-apis/config' },
  ],
  'JavaScript': [
    { name: 'Advanced Features ⭐', href: '/javascript/advanced-features' },
  ],
  'Guides': [
    { name: 'Redux Toolkit', href: '/guides/state-management/redux-toolkit' },
    { name: 'Zustand', href: '/guides/state-management/zustand' },
  ],
  'GraphQL & APIs': [
    { name: 'GraphQL Basics', href: '/graphql/basics' },
    { name: 'Apollo Client', href: '/graphql/apollo-client' },
    { name: 'GraphQL Queries', href: '/graphql/queries' },
    { name: 'GraphQL Mutations', href: '/graphql/mutations' },
    { name: 'Webhooks', href: '/apis/webhooks' },
    { name: 'SOAP', href: '/apis/soap' },
    { name: 'gRPC', href: '/apis/grpc' },
  ],
  'Real-Time': [
    { name: 'WebSockets', href: '/real-time/websockets' },
    { name: 'RxJS Observables', href: '/real-time/rxjs' },
    { name: 'Real-Time UI', href: '/real-time/ui-communication' },
    { name: 'Event-Driven UI', href: '/real-time/event-driven' },
  ],
  'Build Tools': [
    { name: 'Webpack Basics', href: '/build-tools/webpack' },
    { name: 'Turbopack', href: '/build-tools/turbopack' },
    { name: 'SPA Concepts', href: '/build-tools/spa' },
    { name: 'Performance Optimization', href: '/build-tools/performance' },
  ],
  'UI Libraries': [
    { name: 'AG Grid', href: '/ui-libraries/ag-grid' },
    { name: 'Storybook', href: '/ui-libraries/storybook' },
    { name: 'Three.js', href: '/ui-libraries/three' },
    { name: 'Animate.css', href: '/ui-libraries/animate' },
    { name: 'PixiJS', href: '/ui-libraries/pixel' },
  ],
  'DevOps & Tools': [
    { name: 'Docker Basics', href: '/devops/docker' },
    { name: 'Prometheus Monitoring', href: '/devops/prometheus' },
    { name: 'DataDog', href: '/tools/datadog' },
    { name: 'Turborepo', href: '/tools/turborepo' },
  ],
  'Data Fetching & ORMs': [
    { name: 'TanStack Query', href: '/data-fetching/tanstack-query' },
    { name: 'Prisma ORM', href: '/data-fetching/orm-prisma' },
  ],
  'Authentication': [
    { name: 'JWT Authentication', href: '/auth/jwt' },
  ],
  'CI/CD': [
    { name: 'CI/CD Pipelines', href: '/cicd/pipelines' },
  ],
  'Cloud': [
    { name: 'AWS Basics', href: '/cloud/aws' },
    { name: 'Azure Basics', href: '/cloud/azure' },
    { name: 'Cloud Architectures', href: '/cloud/architectures' },
  ],
  'Data Structures': [
    { name: 'Basic Structures', href: '/data-structures/basic' },
    { name: 'Advanced Structures', href: '/data-structures/advanced' },
  ],
  'Algorithms': [
    { name: 'Basic Algorithms', href: '/algorithms/basic' },
    { name: 'Advanced Algorithms', href: '/algorithms/advanced' },
    { name: 'Big O Notation', href: '/algorithms/big-o' },
  ],
  'Software Design': [
    { name: 'Design Principles', href: '/design/principles' },
    { name: 'Accessibility (WCAG)', href: '/design/accessibility' },
  ],
  'Progressive Web Apps': [
    { name: 'PWA Basics', href: '/pwa/basics' },
  ],
  'Methodologies': [
    { name: 'Scrum Framework', href: '/methodologies/scrum' },
  ],
  'Testing': [
    { name: 'TDD', href: '/testing/tdd' },
    { name: 'Unit Testing', href: '/testing/unit' },
    { name: 'Integration Testing', href: '/testing/integration' },
    { name: 'E2E Testing', href: '/testing/e2e' },
    { name: 'Jest', href: '/testing/jest' },
    { name: 'Mocha', href: '/testing/mocha' },
    { name: 'Cypress', href: '/testing/cypress' },
    { name: 'Karma', href: '/testing/karma' },
    { name: 'Enzyme', href: '/testing/enzyme' },
    { name: 'Enzyme + Jest', href: '/testing/enzyme-jest' },
    { name: 'React Testing Library', href: '/testing/react-testing-library' },
  ],
  'Mobile Development': [
    { name: 'Capacitor.js', href: '/mobile/capacitor' },
    { name: 'Cordova.js', href: '/mobile/cordova' },
  ],
  'TypeScript': [
    { name: 'TypeScript Basics', href: '/typescript/basics' },
    { name: 'Advanced TypeScript', href: '/typescript/advanced' },
    { name: 'Generics', href: '/typescript/generics' },
    { name: 'Type Guards', href: '/typescript/type-guards' },
    { name: 'Utility Types', href: '/typescript/utility-types' },
    { name: 'Mapped Types', href: '/typescript/mapped-types' },
    { name: 'Conditional Types', href: '/typescript/conditional-types' },
    { name: 'Decorators', href: '/typescript/decorators' },
  ],
  'Security': [
    { name: 'Frontend Security', href: '/security/frontend' },
  ],
  'Validation': [
    { name: 'Zod Validation', href: '/validation/zod' },
  ],
  'Performance': [
    { name: 'Rate Limiting', href: '/performance/rate-limiting' },
  ],
  'Soft Skills': [
    { name: 'Tech Lead Skills', href: '/soft-skills/tech-lead' },
    { name: 'Stakeholder Management', href: '/soft-skills/stakeholders' },
  ],
};
