/**
 * Navigation data for the application
 * Contains all navigation categories and their respective items
 * 
 * @module constants/navigation
 */

import type { NavigationCategory } from '../types/navigation';

export const NAVIGATION_DATA: NavigationCategory = {
  'React Hooks': [
    { name: 'useState', href: '/hooks/useState' },
    { name: 'useEffect', href: '/hooks/useEffect' },
    { name: 'useContext', href: '/hooks/useContext' },
    { name: 'useReducer', href: '/hooks/useReducer' },
    { name: 'useCallback', href: '/hooks/useCallback' },
    { name: 'useMemo', href: '/hooks/useMemo' },
    { name: 'useRef', href: '/hooks/useRef' },
    { name: 'useLayoutEffect', href: '/hooks/useLayoutEffect' },
    { name: 'useImperativeHandle', href: '/hooks/useImperativeHandle' },
    { name: 'useDebugValue', href: '/hooks/useDebugValue' },
    { name: 'useDeferredValue', href: '/hooks/useDeferredValue' },
    { name: 'useTransition', href: '/hooks/useTransition' },
    { name: 'useId', href: '/hooks/useId' },
    { name: 'useSyncExternalStore', href: '/hooks/useSyncExternalStore' },
    { name: 'useInsertionEffect', href: '/hooks/useInsertionEffect' },
    { name: 'use', href: '/hooks/use' },
  ],
  'Patterns': [
    { name: 'Compound Components', href: '/patterns/compound-components' },
    { name: 'Higher-Order Component', href: '/patterns/higher-order-component' },
    { name: 'Render Props', href: '/patterns/render-props' },
    { name: 'Container/Presentational', href: '/patterns/container-presentational' },
    { name: 'Provider Pattern', href: '/patterns/provider-pattern' },
    { name: 'Custom Hooks', href: '/patterns/custom-hooks' },
    { name: 'Controlled vs Uncontrolled', href: '/patterns/controlled-uncontrolled' },
    { name: 'State Reducer', href: '/patterns/state-reducer' },
    { name: 'Props Getter', href: '/patterns/props-getter' },
    { name: 'Conditional Rendering', href: '/patterns/conditional-rendering' },
    { name: 'Layout Pattern', href: '/patterns/layout-pattern' },
    { name: 'Observer Pattern', href: '/patterns/observer-pattern' },
    { name: 'Module Pattern', href: '/patterns/module-pattern' },
    { name: 'Singleton Pattern', href: '/patterns/singleton-pattern' },
    { name: 'Proxy Pattern', href: '/patterns/proxy-pattern' },
    { name: 'Factory Pattern', href: '/patterns/factory-pattern' },
    { name: 'Adapter Pattern', href: '/patterns/adapter-pattern' },
    { name: 'Decorator Pattern', href: '/patterns/decorator-pattern' },
    { name: 'Strategy Pattern', href: '/patterns/strategy-pattern' },
    { name: 'Command Pattern', href: '/patterns/command-pattern' },
    { name: 'Facade Pattern', href: '/patterns/facade-pattern' },
  ],
  'Architectures': [
    { name: 'Atomic Design', href: '/architectures/atomic-design' },
    { name: 'Feature-Sliced Design', href: '/architectures/feature-sliced-design' },
    { name: 'Micro Frontends', href: '/architectures/micro-frontends' },
    { name: 'Clean Architecture', href: '/architectures/clean-architecture' },
    { name: 'Hexagonal Architecture', href: '/architectures/hexagonal-architecture' },
    { name: 'Layered Architecture', href: '/architectures/layered-architecture' },
    { name: 'Microservices Architecture', href: '/architectures/microservices-architecture' },
    { name: 'MVC Architecture', href: '/architectures/mvc-architecture' },
  ],
  'State Management': [
    { name: 'Redux Toolkit', href: '/state-management/redux-toolkit' },
    { name: 'Zustand', href: '/state-management/zustand' },
  ],
  'React APIs': [
    { name: 'React.createElement', href: '/react-apis/createElement' },
    { name: 'React.Children', href: '/react-apis/Children' },
    { name: 'React.Fragment', href: '/react-apis/Fragment' },
    { name: 'React.memo', href: '/react-apis/memo' },
    { name: 'React.lazy & Suspense', href: '/react-apis/lazy-suspense' },
    { name: 'React.StrictMode', href: '/react-apis/StrictMode' },
    { name: 'React.createRef', href: '/react-apis/createRef' },
    { name: 'React.forwardRef', href: '/react-apis/forwardRef' },
    { name: 'React.cloneElement', href: '/react-apis/cloneElement' },
    { name: 'React.isValidElement', href: '/react-apis/isValidElement' },
    { name: 'React.Component', href: '/react-apis/Component' },
    { name: 'React.PureComponent', href: '/react-apis/PureComponent' },
    { name: 'React.Profiler', href: '/react-apis/Profiler' },
    { name: 'React.startTransition', href: '/react-apis/startTransition' },
    { name: 'React.createPortal', href: '/react-apis/createPortal' },
    { name: 'React.createContext', href: '/react-apis/createContext' },
  ],
  'Next.js APIs': [
    { name: 'next/link', href: '/nextjs-apis/link' },
    { name: 'next/router', href: '/nextjs-apis/router' },
    { name: 'next/image', href: '/nextjs-apis/image' },
    { name: 'next/script', href: '/nextjs-apis/script' },
    { name: 'next/head', href: '/nextjs-apis/head' },
    { name: 'next/dynamic', href: '/nextjs-apis/dynamic' },
    { name: 'next/navigation', href: '/nextjs-apis/navigation' },
    { name: 'next/headers', href: '/nextjs-apis/headers' },
    { name: 'next/server', href: '/nextjs-apis/server' },
    { name: 'next/font', href: '/nextjs-apis/font' },
    { name: 'next/config', href: '/nextjs-apis/config' },
  ],
  'Guides': [
    { name: 'Redux Toolkit', href: '/guides/state-management/redux-toolkit' },
    { name: 'Zustand', href: '/guides/state-management/zustand' },
  ],
};
