import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
// import localFont from 'next/font/local';
import "./globals.css";

// Configure Google Fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

// Configure Local Font
// const customLocalFont = localFont({
//   src: '../../public/fonts/YourCustomFont.woff2',
//   variable: '--font-custom',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} `}
      >
        {children}
      </body>
    </html>
  );
}